/// Initial SQLite schema, translated from the old Postgres/SQLAlchemy models in
/// `snapcapsule_core/models/entities.py`. Notable translations:
/// - `UUID` -> `TEXT` (uuid v4 string, generated by the caller before insert)
/// - `JSON`/`JSONB` -> `TEXT` (JSON-encoded string, parsed on the fly)
/// - `Enum` -> `TEXT` with a `CHECK` constraint standing in for Postgres enum types
/// - `Boolean` -> `INTEGER` (0/1), SQLite has no native boolean type
/// - `DateTime(timezone=True)` -> `TEXT` (ISO 8601 UTC string)
/// - `onupdate=func.now()` -> an `AFTER UPDATE` trigger per table, since SQLite
///   has no column-level auto-update-on-write
/// - `celery_task_id` on `ingestion_jobs` dropped: Celery is server infra this
///   project explicitly excludes (see AGENT.md's architectural rules)
/// - the Postgres GIN index on `assets.tags` has no SQLite equivalent for a
///   JSON-in-TEXT column; deferred until tag search is actually implemented
/// - `assets.latitude`/`longitude` have no equivalent in the old models at all:
///   the old app only ever stored account-level location summaries as opaque
///   strings, never per-memory GPS. Newer Snapchat exports include a
///   `Location` field per `memories_history.json` entry, so this is new.
pub const SCHEMA_SQL: &str = r#"
CREATE TABLE IF NOT EXISTS assets (
    id TEXT PRIMARY KEY,
    external_id TEXT,
    source_type TEXT NOT NULL DEFAULT 'unknown'
        CHECK (source_type IN ('chat', 'memory', 'story', 'unknown')),
    media_type TEXT NOT NULL
        CHECK (media_type IN ('image', 'video', 'audio')),
    original_path TEXT NOT NULL UNIQUE,
    thumbnail_path TEXT,
    playback_path TEXT,
    overlay_path TEXT,
    checksum_sha256 TEXT,
    file_size_bytes INTEGER,
    taken_at TEXT,
    latitude REAL,
    longitude REAL,
    is_favorite INTEGER NOT NULL DEFAULT 0,
    tags TEXT NOT NULL DEFAULT '[]',
    raw_metadata TEXT,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE INDEX IF NOT EXISTS ix_assets_external_id ON assets (external_id);
CREATE INDEX IF NOT EXISTS ix_assets_checksum_sha256 ON assets (checksum_sha256);
CREATE INDEX IF NOT EXISTS ix_assets_media_type ON assets (media_type);
CREATE INDEX IF NOT EXISTS ix_assets_taken_at_media_type ON assets (taken_at, media_type);
CREATE INDEX IF NOT EXISTS ix_assets_source_type_taken_at ON assets (source_type, taken_at);
CREATE INDEX IF NOT EXISTS ix_assets_source_type_media_type_taken_at ON assets (source_type, media_type, taken_at);
CREATE INDEX IF NOT EXISTS ix_assets_is_favorite ON assets (is_favorite);
CREATE TRIGGER IF NOT EXISTS trg_assets_updated_at
AFTER UPDATE ON assets FOR EACH ROW
BEGIN
    UPDATE assets SET updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE id = old.id;
END;

CREATE TABLE IF NOT EXISTS ingestion_jobs (
    id TEXT PRIMARY KEY,
    source_kind TEXT NOT NULL
        CHECK (source_kind IN ('upload', 'directory')),
    source_name TEXT NOT NULL,
    source_path TEXT NOT NULL,
    workspace_path TEXT,
    status TEXT NOT NULL DEFAULT 'queued'
        CHECK (status IN ('queued', 'extracting', 'parsing', 'processing_media', 'completed', 'canceled', 'failed')),
    detail_message TEXT,
    progress_percent INTEGER NOT NULL DEFAULT 0,
    total_assets INTEGER NOT NULL DEFAULT 0,
    processed_assets INTEGER NOT NULL DEFAULT 0,
    failed_assets INTEGER NOT NULL DEFAULT 0,
    error_message TEXT,
    finished_at TEXT,
    raw_metadata TEXT,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE INDEX IF NOT EXISTS ix_ingestion_jobs_status_created_at ON ingestion_jobs (status, created_at);
CREATE TRIGGER IF NOT EXISTS trg_ingestion_jobs_updated_at
AFTER UPDATE ON ingestion_jobs FOR EACH ROW
BEGIN
    UPDATE ingestion_jobs SET updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE id = old.id;
END;

CREATE TABLE IF NOT EXISTS profile_snapshots (
    id INTEGER PRIMARY KEY,
    generated_at TEXT,
    snapshot TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE TRIGGER IF NOT EXISTS trg_profile_snapshots_updated_at
AFTER UPDATE ON profile_snapshots FOR EACH ROW
BEGIN
    UPDATE profile_snapshots SET updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE id = old.id;
END;

CREATE TABLE IF NOT EXISTS chat_threads (
    id TEXT PRIMARY KEY,
    external_id TEXT NOT NULL UNIQUE,
    title TEXT,
    is_group INTEGER NOT NULL DEFAULT 0,
    raw_metadata TEXT,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE INDEX IF NOT EXISTS ix_chat_threads_title ON chat_threads (title);
CREATE TRIGGER IF NOT EXISTS trg_chat_threads_updated_at
AFTER UPDATE ON chat_threads FOR EACH ROW
BEGIN
    UPDATE chat_threads SET updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE id = old.id;
END;

CREATE TABLE IF NOT EXISTS chat_messages (
    id TEXT PRIMARY KEY,
    thread_id TEXT NOT NULL REFERENCES chat_threads (id) ON DELETE CASCADE,
    sender TEXT NOT NULL,
    body TEXT,
    sent_at TEXT NOT NULL,
    message_type TEXT NOT NULL DEFAULT 'TEXT',
    source TEXT NOT NULL DEFAULT 'chat_history'
        CHECK (source IN ('chat_history', 'snap_history')),
    dedupe_key TEXT NOT NULL UNIQUE,
    raw_media_ids TEXT,
    raw_payload TEXT,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE INDEX IF NOT EXISTS ix_chat_messages_thread_sent_at ON chat_messages (thread_id, sent_at);
CREATE INDEX IF NOT EXISTS ix_chat_messages_sent_at ON chat_messages (sent_at);
CREATE TRIGGER IF NOT EXISTS trg_chat_messages_updated_at
AFTER UPDATE ON chat_messages FOR EACH ROW
BEGIN
    UPDATE chat_messages SET updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE id = old.id;
END;

CREATE TABLE IF NOT EXISTS chat_message_assets (
    message_id TEXT NOT NULL REFERENCES chat_messages (id) ON DELETE CASCADE,
    asset_id TEXT NOT NULL REFERENCES assets (id) ON DELETE CASCADE,
    PRIMARY KEY (message_id, asset_id)
);
CREATE INDEX IF NOT EXISTS ix_chat_message_assets_asset_id ON chat_message_assets (asset_id);

CREATE TABLE IF NOT EXISTS memory_collections (
    id TEXT PRIMARY KEY,
    external_id TEXT UNIQUE,
    title TEXT NOT NULL DEFAULT 'Saved Media',
    raw_metadata TEXT,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE TRIGGER IF NOT EXISTS trg_memory_collections_updated_at
AFTER UPDATE ON memory_collections FOR EACH ROW
BEGIN
    UPDATE memory_collections SET updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE id = old.id;
END;

CREATE TABLE IF NOT EXISTS memory_items (
    id TEXT PRIMARY KEY,
    collection_id TEXT NOT NULL REFERENCES memory_collections (id) ON DELETE CASCADE,
    asset_id TEXT NOT NULL REFERENCES assets (id) ON DELETE CASCADE,
    taken_at TEXT,
    position INTEGER,
    raw_payload TEXT,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    UNIQUE (collection_id, asset_id)
);
CREATE INDEX IF NOT EXISTS ix_memory_items_taken_at ON memory_items (taken_at);
CREATE INDEX IF NOT EXISTS ix_memory_items_asset_taken_at_position ON memory_items (asset_id, taken_at, position);
CREATE TRIGGER IF NOT EXISTS trg_memory_items_updated_at
AFTER UPDATE ON memory_items FOR EACH ROW
BEGIN
    UPDATE memory_items SET updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE id = old.id;
END;

CREATE TABLE IF NOT EXISTS story_collections (
    id TEXT PRIMARY KEY,
    external_id TEXT UNIQUE,
    title TEXT,
    story_type TEXT NOT NULL DEFAULT 'unknown'
        CHECK (story_type IN ('private', 'public', 'saved', 'unknown')),
    raw_metadata TEXT,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE TRIGGER IF NOT EXISTS trg_story_collections_updated_at
AFTER UPDATE ON story_collections FOR EACH ROW
BEGIN
    UPDATE story_collections SET updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE id = old.id;
END;

CREATE TABLE IF NOT EXISTS story_items (
    id TEXT PRIMARY KEY,
    collection_id TEXT NOT NULL REFERENCES story_collections (id) ON DELETE CASCADE,
    asset_id TEXT NOT NULL REFERENCES assets (id) ON DELETE CASCADE,
    posted_at TEXT,
    position INTEGER,
    raw_payload TEXT,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    UNIQUE (collection_id, asset_id)
);
CREATE INDEX IF NOT EXISTS ix_story_items_posted_at ON story_items (posted_at);
CREATE INDEX IF NOT EXISTS ix_story_items_collection_position ON story_items (collection_id, position);
CREATE TRIGGER IF NOT EXISTS trg_story_items_updated_at
AFTER UPDATE ON story_items FOR EACH ROW
BEGIN
    UPDATE story_items SET updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE id = old.id;
END;
"#;

#[cfg(test)]
mod tests {
    use super::SCHEMA_SQL;
    use rusqlite::Connection;

    fn expected_tables() -> Vec<&'static str> {
        vec![
            "assets",
            "chat_message_assets",
            "chat_messages",
            "chat_threads",
            "ingestion_jobs",
            "memory_collections",
            "memory_items",
            "profile_snapshots",
            "story_collections",
            "story_items",
        ]
    }

    #[test]
    fn schema_applies_cleanly() {
        let conn = Connection::open_in_memory().unwrap();
        conn.execute_batch("PRAGMA foreign_keys = ON;").unwrap();
        conn.execute_batch(SCHEMA_SQL).unwrap();

        let mut stmt = conn
            .prepare("SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%' ORDER BY name")
            .unwrap();
        let tables: Vec<String> = stmt
            .query_map([], |row| row.get(0))
            .unwrap()
            .collect::<Result<_, _>>()
            .unwrap();

        assert_eq!(tables, expected_tables());
    }

    #[test]
    fn schema_is_idempotent() {
        let conn = Connection::open_in_memory().unwrap();
        conn.execute_batch(SCHEMA_SQL).unwrap();
        // Applying twice must not error (mirrors calling init on every app launch).
        conn.execute_batch(SCHEMA_SQL).unwrap();
    }

    #[test]
    fn enum_check_constraints_reject_invalid_values() {
        let conn = Connection::open_in_memory().unwrap();
        conn.execute_batch(SCHEMA_SQL).unwrap();

        let result = conn.execute(
            "INSERT INTO assets (id, media_type, original_path) VALUES ('a1', 'not-a-real-type', '/tmp/a')",
            [],
        );
        assert!(result.is_err());
    }

    #[test]
    fn cascade_delete_removes_dependent_rows() {
        let conn = Connection::open_in_memory().unwrap();
        conn.execute_batch("PRAGMA foreign_keys = ON;").unwrap();
        conn.execute_batch(SCHEMA_SQL).unwrap();

        conn.execute(
            "INSERT INTO memory_collections (id, title) VALUES ('c1', 'Test')",
            [],
        )
        .unwrap();
        conn.execute(
            "INSERT INTO assets (id, media_type, original_path) VALUES ('a1', 'image', '/tmp/a.jpg')",
            [],
        )
        .unwrap();
        conn.execute(
            "INSERT INTO memory_items (id, collection_id, asset_id) VALUES ('m1', 'c1', 'a1')",
            [],
        )
        .unwrap();

        conn.execute("DELETE FROM memory_collections WHERE id = 'c1'", [])
            .unwrap();

        let remaining: i64 = conn
            .query_row("SELECT COUNT(*) FROM memory_items", [], |row| row.get(0))
            .unwrap();
        assert_eq!(remaining, 0);
    }

    #[test]
    fn updated_at_trigger_bumps_timestamp_on_write() {
        let conn = Connection::open_in_memory().unwrap();
        conn.execute_batch(SCHEMA_SQL).unwrap();

        conn.execute(
            "INSERT INTO chat_threads (id, external_id) VALUES ('t1', 'ext-1')",
            [],
        )
        .unwrap();
        let created_at: String = conn
            .query_row("SELECT created_at FROM chat_threads WHERE id = 't1'", [], |row| {
                row.get(0)
            })
            .unwrap();

        std::thread::sleep(std::time::Duration::from_millis(10));
        conn.execute(
            "UPDATE chat_threads SET title = 'Renamed' WHERE id = 't1'",
            [],
        )
        .unwrap();
        let updated_at: String = conn
            .query_row("SELECT updated_at FROM chat_threads WHERE id = 't1'", [], |row| {
                row.get(0)
            })
            .unwrap();

        assert_ne!(created_at, updated_at);
    }
}
